// Generated by Wrangler on Tue Oct 15 2024 16:35:30 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	SHORT_URLS: KVNamespace;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
}
