#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-remix"
compatibility_date = "2024-10-11"
pages_build_output_dir = "./build/client"

[vars]
SUPABASE_URL = "https://example.supabase.co"
SUPABASE_ANON_KEY = "example"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#kv-namespaces
[[kv_namespaces]]
binding = "SHORT_URLS"
id = "example"
preview_id = "example"
